# Assignment -03-Q1

In [2]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [5]:
data = pd.read_csv(r"C:\Users\Mohan Patil\OneDrive\Desktop\Datasets\Cutlets.csv")

In [7]:
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [9]:
UnitA=pd.Series(data.iloc[:,0])

In [10]:
UnitA.head()

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
Name: Unit A, dtype: float64

In [11]:
UnitB = pd.Series(data.iloc[:,1])

In [12]:
UnitB.head()

0    6.7703
1    7.5093
2    6.7300
3    6.7878
4    7.1522
Name: Unit B, dtype: float64

In [13]:
# 2-Sample 2-tail ttest:stats.ttest_ind(array1,array2) (ind-Independent Sample)
p_value=stats.ttest_ind(UnitA,UnitB)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [14]:
p_value[1]

0.4722394724599501

In [15]:
# compare p_value with α = 0.05 (At 5% significance level)
# p_value > α = 0.05

# Assignment -03-Q2

In [16]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [18]:
# Load the data Set
data1 =pd.read_csv(r"C:\Users\Mohan Patil\OneDrive\Desktop\Datasets\LabTAT.csv")
data1

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [23]:
data1.dtypes

Laboratory 1    float64
Laboratory 2    float64
Laboratory 3    float64
Laboratory 4    float64
dtype: object

In [24]:
# Anova ftest Statistics:stats.f_oneway(Column1,Column2,Column3,Column4)
p_value1=stats.f_oneway(data1.iloc[:,0],data1.iloc[:,1],data1.iloc[:,2],data1.iloc[:,3])
p_value1

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [25]:
p_value1[1]

2.1156708949992414e-57

In [26]:
# compare p_value with α = 0.05 (At 5% significance level)
# p_value1 < α = 0.05

# Assignment -03-Q3

In [27]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [29]:
data2 = pd.read_csv(r"C:\Users\Mohan Patil\OneDrive\Desktop\Datasets\BuyerRatio (1).csv")

In [30]:
data2.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [35]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Observed Values  2 non-null      object
 1   East             2 non-null      int64 
 2   West             2 non-null      int64 
 3   North            2 non-null      int64 
 4   South            2 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 208.0+ bytes


In [36]:
# Make dimensional Array
obs = np.array([[50,142,131,70],[435,1523,1356,750]])
obs

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [60]:
# Chi2 contengency independence test
chi2_contingency(obs)
# It will give ('Chi2 stats value','p_value','df','expected obsvations')

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [61]:
# p_value = 0.6603
#  α = 0.05

In [62]:
# p_value > α value so Accept the null hypothesis , categorical variable are Independance

# Assignment -03-Q4

In [45]:
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [48]:
# load the data
data3 = pd.read_csv(r"C:\Users\Mohan Patil\OneDrive\Desktop\Datasets\Costomer+OrderForm.csv")
data3.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [47]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [49]:
# null hypothesis(Ho)=independance of Categorical Variable(customer order forms defective % does not varies by centre)
# alternative hypothesis(Ha)=Dependance of Categorical Variable(customer order forms defective % varies by centre)

In [53]:
data3.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [54]:
data3.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [55]:
data3.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [56]:
data3.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [57]:
# make Contigency Table
obs0 = np.array([[271,267, 269, 280],[29,  33,  31,  20]])
obs0

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [63]:
# Chi2 Contengency independance test
chi2_contingency(obs0)
# It will give ('Chi2 stats value','p_value','df','expected obsvations')

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [64]:
# Compare p_value=0.2771 with α = 0.05

In [65]:
# Accept Null Hypthesis i.e. Independence of categorical variables